### ISSUE TITLE
About settings.py startup configuration

### ISSUE THREAD

**Issue by ZhiwenDeng-dev** [longd3/mj-remit#1]
hi,bro,i saw the consul-example.json example, but I don’t know the parameters in it. Those are the ones that must be configured and those are optional. In addition, what do these parameters mean and where to get them, can you give a detailed introduction ? Thank you very much, this is very helpful for me
   "MJD_APP_ID": "936929561302675456",
   "MJD_COMMAND_VERSION_ID": "1077969938624553050",
   "MJD_DATA_COMMAND_ID": "938956540159881230",
   "MJR_TOKEN": "YOUR_BOT_TOKEN",
   "IMPERSONATOR_TOKEN": "IMPERSONATOR_TOKEN (with MJ subscription)",
   "DISCORD_SERVER_ID": "Your Discord server(guild) id",
   "DISCORD_CHANNEL_ID": "Your fixed Discord channel (that you want MJR in) id",
   "SLOGAN": "Lucky you!",
   "SESSION_ID": "Use UUID4 with no dash",
   "RABBITMQ_URL": "amqp://YOUR_RABBITMQ",
   "RABBITMQ_EXCHANGE_MJ_EVENT": "MJ_EVENT",
   "RABBITMQ_QUEUE_MJ_EVENT_URL": "YOUR_RABBITMQ_MJ_EVENT_QUEUE_URL",
   "MONGODB_URL": "mongodb://YOUR_MONGO",
   "MONGODB_COLLECTION_RAW_RESPONSES": "raw_responses",
   "MONGODB_COLLECTION_ARTWORKS": "artworks",
   "MONGODB_COLLECTION_MJR_LOGS": "mjr_logs"

**Comment by longd3** [comment]
hi @ZhiwenDeng-dev I will provide more details on README soon, stay tuned!

**Comment by longd3** [comment]
@ZhiwenDeng-dev please check latest README.md, enjoy!
